# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12meterservice.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n\rReadingPacket\x12!\n\x08Readings\x18\x01 \x03(\x0b\x32\x0f.ReadingMessage\x12\"\n\nSuccessful\x18\x02 \x01(\x0e\x32\x0e.ReadingStatus\"\x8c\x01\n\x0eReadingMessage\x12\x12\n\ncustomerId\x18\x01 \x01(\x05\x12\x14\n\x0cReadingValue\x18\x02 \x01(\x05\x12\r\n\x05Notes\x18\x03 \x01(\t\x12/\n\x0bReadingTime\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x04\x10\x05R\nSuccessful\">\n\rStatusMessage\x12\x1e\n\x06Status\x18\x01 \x01(\x0e\x32\x0e.ReadingStatus\x12\r\n\x05Notes\x18\x02 \x01(\t*6\n\rReadingStatus\x12\x0b\n\x07Unknown\x10\x00\x12\x0b\n\x07Success\x10\x01\x12\x0b\n\x07\x46\x61ilure\x10\x02\x32\x42\n\x12MeterReaderService\x12,\n\nAddReading\x12\x0e.ReadingPacket\x1a\x0e.StatusMessageB\x13\xaa\x02\x10MeterReader.gRPCb\x06proto3')

_READINGSTATUS = DESCRIPTOR.enum_types_by_name['ReadingStatus']
ReadingStatus = enum_type_wrapper.EnumTypeWrapper(_READINGSTATUS)
Unknown = 0
Success = 1
Failure = 2


_READINGPACKET = DESCRIPTOR.message_types_by_name['ReadingPacket']
_READINGMESSAGE = DESCRIPTOR.message_types_by_name['ReadingMessage']
_STATUSMESSAGE = DESCRIPTOR.message_types_by_name['StatusMessage']
ReadingPacket = _reflection.GeneratedProtocolMessageType('ReadingPacket', (_message.Message,), {
  'DESCRIPTOR' : _READINGPACKET,
  '__module__' : 'meterservice_pb2'
  # @@protoc_insertion_point(class_scope:ReadingPacket)
  })
_sym_db.RegisterMessage(ReadingPacket)

ReadingMessage = _reflection.GeneratedProtocolMessageType('ReadingMessage', (_message.Message,), {
  'DESCRIPTOR' : _READINGMESSAGE,
  '__module__' : 'meterservice_pb2'
  # @@protoc_insertion_point(class_scope:ReadingMessage)
  })
_sym_db.RegisterMessage(ReadingMessage)

StatusMessage = _reflection.GeneratedProtocolMessageType('StatusMessage', (_message.Message,), {
  'DESCRIPTOR' : _STATUSMESSAGE,
  '__module__' : 'meterservice_pb2'
  # @@protoc_insertion_point(class_scope:StatusMessage)
  })
_sym_db.RegisterMessage(StatusMessage)

_METERREADERSERVICE = DESCRIPTOR.services_by_name['MeterReaderService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\020MeterReader.gRPC'
  _READINGSTATUS._serialized_start=350
  _READINGSTATUS._serialized_end=404
  _READINGPACKET._serialized_start=55
  _READINGPACKET._serialized_end=141
  _READINGMESSAGE._serialized_start=144
  _READINGMESSAGE._serialized_end=284
  _STATUSMESSAGE._serialized_start=286
  _STATUSMESSAGE._serialized_end=348
  _METERREADERSERVICE._serialized_start=406
  _METERREADERSERVICE._serialized_end=472
# @@protoc_insertion_point(module_scope)
